In [4]:
import torch 
random=torch.rand(3,4)
print(random)
random.ndim
random.shape

tensor([[0.4588, 0.4881, 0.6980, 0.2964],
        [0.3297, 0.7573, 0.0518, 0.1994],
        [0.2879, 0.1865, 0.4654, 0.8285]])


torch.Size([3, 4])

In [9]:
random1=torch.rand(2,3,4)   #Each number represents the 1 dim here 3 numbers are given means 3 dim ndim means how many brackets u need to go thru to reach an element/array
print(random1)
random1.ndim
random1.shape
#2 means in first bracket there are 2 data 3 means 3 rows of data and 4 means 4 elements inside 3 rows of 2 table data

tensor([[[0.8179, 0.6661, 0.9021, 0.2506],
         [0.6732, 0.9677, 0.1738, 0.5164],
         [0.7739, 0.4476, 0.5359, 0.5452]],

        [[0.1142, 0.9146, 0.0607, 0.1851],
         [0.5555, 0.9457, 0.7154, 0.7563],
         [0.4872, 0.0461, 0.9146, 0.0836]]])


torch.Size([2, 3, 4])

In [11]:
data=torch.tensor([1,2,3])
data

tensor([1, 2, 3])

In [15]:
random2=torch.rand(2,2,3,4)   # or random2=torch.rand(size=(2,2,3,4)) both are same things
random2
# random2.ndim
#here 2 is the first highest block in which 2 table/data(2x3x4) is there in that a sub data containing 2 data block of 3x4 each

tensor([[[[0.9142, 0.7123, 0.0838, 0.3656],
          [0.1810, 0.4787, 0.7852, 0.0828],
          [0.2107, 0.5772, 0.6287, 0.6004]],

         [[0.4123, 0.5242, 0.1847, 0.5225],
          [0.7618, 0.8735, 0.5360, 0.2182],
          [0.9862, 0.9653, 0.4850, 0.2967]]],


        [[[0.7478, 0.6561, 0.6810, 0.7876],
          [0.6757, 0.3816, 0.7554, 0.5117],
          [0.2855, 0.7455, 0.6740, 0.9384]],

         [[0.9150, 0.8555, 0.6868, 0.7262],
          [0.4350, 0.8374, 0.4230, 0.8646],
          [0.9377, 0.9422, 0.5245, 0.1640]]]])

In [23]:
random3=torch.rand(size=(3,224,224))
# random3.shape
# random3.ndim
# random3

In [22]:
zeros=torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones=torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [31]:
numbers=torch.arange(1,10)
zeros1=torch.zeros_like(input=numbers)
print(zeros1) # it will give everything as zero output for whatever number or input we have passed

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])


In [28]:
value=torch.arange(start=1,end=1000,step=20)
value

tensor([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181, 201, 221, 241, 261,
        281, 301, 321, 341, 361, 381, 401, 421, 441, 461, 481, 501, 521, 541,
        561, 581, 601, 621, 641, 661, 681, 701, 721, 741, 761, 781, 801, 821,
        841, 861, 881, 901, 921, 941, 961, 981])

In [38]:
number1=torch.tensor([1.0,2.0,3.0],dtype=None,device=None,
                     requires_grad=False) #whether to track or not to track gradients with this tensors operations 
number1.dtype

torch.float32

In [37]:
convert_to_float16=number1.type(torch.float16)  #convert the datatype 
convert_to_float16

tensor([1., 2., 3.], dtype=torch.float16)

In [40]:
number1*convert_to_float16

tensor([1., 4., 9.])